### ISSUE TITLE
LCP Integration

### ISSUE THREAD

**Issue by leomoty** [edrlab/r2-lcp-js#2]
As requested, I am not currently at work, will be there shortly. Anyways, I am running all the 3 webservers from https://github.com/readium/readium-lcp-server.

It seems to work fine-ish, I am yet unsure about a few `config.yaml` bits, mostly the publication one. When I get to work I can share my yaml file.

As background, I work for a university in southern Brazil that has a self-publishing arm and want to leverage some sort of ebook publication. I was tasked to take a look into our options.

**Comment by leomoty** [comment]
config.yaml:
```
profile: "basic"
lcp:
    host: "192.168.10.97"
    port: 8989
    public_base_url: "http://192.168.10.97:8989"
    database: "sqlite3://file:/readiumlcp/lcpdb/lcp.sqlite?cache=shared&mode=rwc"
    auth_file: "/readiumlcp/lcpconfig/htpasswd"
storage:
    filesystem:
        directory: "/readiumlcp/lcpfiles/encrypted"
certificate:
    cert: "/readiumlcp/lcpconfig/cert.pem"
    private_key: "/readiumlcp/lcpconfig/privkey.pem"
license:
    links:
        status: "http://192.168.10.97:8990/licenses/{license_id}/status"     
        hint: "http://192.168.10.97:8991/static/hint.html"
        publication: "http://192.168.10.97:8991/api/v1/licenses/{publication_id}/publication" 
lsd:
    host: "192.168.10.97"
    port: 8990
    public_base_url: "http://192.168.10.97:8990"
    database: "sqlite3://file:/readiumlcp/lcpdb/lsd.sqlite?cache=shared&mode=rwc"
    auth_file: "/readiumlcp/lcpconfig/htpasswd"
    license_link_url: "http://192.168.10.97:8991/api/v1/licenses/licenses/{license_id}"
license_status:
    register: true
    renew: true
    return: true
    renting_days: 60
    renew_days: 7
logging: 
    log_directory: "/readiumlcp/lcpfiles/lsdserver.log"
    compliance_tests_mode_on: false
lsd_notify_auth: 
    username: "adm_username"
    password: "adm_password"
lcp_update_auth: 
    username: "adm_username"
    password: "adm_password"
frontend:
    host: "192.168.10.97"
    port: 8991
    database: "sqlite3://file:/readiumlcp/lcpdb/frontend.sqlite?cache=shared&mode=rwc"
    master_repository: "/readiumlcp/lcpfiles/master"
    encrypted_repository: "/readiumlcp/lcpfiles/encrypted"
    provider_uri: "https://www.edrlab.org"
    right_print: 10
    right_copy: 2000
```

I am using a mostly unchanged config from https://github.com/readium/readium-lcp-server. But notable changes I remember:

* `storage.filesystem.directory` has to point to the same as `frontend.encrypted_repository`? I am not sure, but it didn't move the .tmp file to encrypted otherwise.

* `license.links.publication`, the README has  `{license_id}` as example, it doesn't seem to map, rereading the text portion I changed to `{publication_id}`, I am also not sure whether I should or not include /api/v1/, I saw some discussion regarding this (https://github.com/readium/readium-lcp-server/issues/150)
